### ISSUE TITLE
Add references support

### ISSUE THREAD

**Issue by timhall** [vba-blocks/vba-blocks#18]
Goal:

```toml
[references.VBIDE]
version = "5.3"
guid = "{0002E157-0000-0000-C000-000000000046}"
```

Ran into some issues during development with adding references via the extensiblity API where the couldn't be found for the given guid. Will look into this for the next release.
